name: Release Downloader

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: robinraju/release-downloader@v1
    - name: Release Downloader
      uses: robinraju/release-downloader@v1
      with:
        repository: shadps4-emu/shadPS4
        latest: false
        preRelease: true
        tarBall: false
        zipBall: false
        out-file-path: .
        extract: false
